services:
  psql:
    image: postgis/postgis:16-3.5.0alpha2-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "geo123"
      POSTGRES_DB: "geocomp"
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:



